# Generated by Django 4.0.2 on 2022-04-03 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpage', '0001_initial'),
        ('validate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_total', models.FloatField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validate.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartid', models.IntegerField()),
                ('payment', models.FloatField()),
                ('userinf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validate.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='cartitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartid', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total', models.FloatField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpage.productdetails')),
            ],
        ),
    ]
