# Generated by Django 4.0.2 on 2022-04-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField(default=25)),
                ('productimg', models.ImageField(upload_to='productimgs')),
            ],
        ),
    ]
